### ISSUE TITLE
np.sign(rewards)

### ISSUE THREAD

**Issue by bhairavmehta95** [junhyukoh/self-imitation-learning#2]
Is there a reason that SIL requires using the `np.sign(reward)` to do all of the training, rather than the raw rewards themselves?

**Comment by junhyukoh** [comment]
Many existing works on Atari clip the reward to [-1, 1] to stabilize learning. 
SIL does not require any constraints on the rewards.
In fact, MuJoCo experiments (PPO+SIL) do not use `np.sign(reward)`.

**Comment by bhairavmehta95** [comment]
Thanks!

**Comment by Thoreau-Qi** [comment]
Many thanks
